CREATE DATABASE IF NOT EXISTS $DATA_NAME;
CREATE USER IF NOT EXISTS $USER_NAME@'%' IDENTIFIED BY  '$USER_PASSWORD' ;
GRANT ALL PRIVILEGES ON $DATA_NAME.* TO $USER_NAME@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@localhost IDENTIFIED BY '$ROOT_PASSWORD';
